version: "3"
services:
  tunnel:
    build:
      context: ./client-tunnel
      dockerfile: Dockerfile
    restart: always
    networks:
        - confluentinc
    depends_on:
        - kafka-ui
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - confluentinc
    volumes: 
      - ./zoo_data:/var/lib/zookeeper/data
      - ./zoo_log:/var/lib/zookeeper/log
    restart: always
  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    volumes: 
      - ./kafka1_data:/var/lib/kafka/data
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://TUNNEL_SERVER_IP:29999
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - confluentinc
  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
      - kafka1
    volumes: 
      - ./kafka2_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - confluentinc
    restart: always
  kafka3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    volumes: 
      - ./kafka3_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - confluentinc
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - $UI_PORT:8080
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    networks:
      - confluentinc
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: cluster1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

networks:
  confluentinc:
    driver: bridge
